### ISSUE TITLE
Read Value From Output Module (Question)

### ISSUE THREAD

**Issue by 2BAD2B007** [facts-engineering/P1AM#10]
I have been tinkering with the P1AM-100, and I am having an issue reading the current value from an output module. Looking through the documentation I believe it only supports writeDiscrete(). I was wondering if there is any way to read the status of an output, so I don't have to keep track of the status in a global variable. The output module I am using is a P1-15TD2.

**Comment by AdamCummick** [comment]
You can accomplish this using the readBlockData function. It will require some comfortability with pointers.  
[This example](https://github.com/facts-engineering/P1AM/blob/master/examples/Utility/BlockDataTransfer/BlockDataTransfer.ino) shows how to read and write from a discrete output using the blockData functions.

**Comment by 2BAD2B007** [comment]
Awesome! Thank you for the quick reply. This should work.
