### ISSUE TITLE
Error downloading additional board manager

### ISSUE THREAD

**Issue by jzwi** [facts-engineering/P1AM#11]
I am trying to configure Arduino IDE for the P1AM. I put the URL as in this thread into the additional boards manager and get a download error. As well as when searching for board under manager there is no P1AM. If any one could help point me in the right direction that'd be great

**Comment by AdamCummick** [comment]
What operating system are you on?
What version of the Arduino IDE are you using?
Are you on any sort of managed or corporate network?

**Comment by jzwi** [comment]
Windows 10.
I tried on 1.8.12 and 1.8.15
and yes, so I imagine it has to be some sort of firewall issue?

**Comment by AdamCummick** [comment]
I've seen that be the issue once or twice. We do have a packaged portable install, though it is slightly out of date. Before we go down that road could you check a couple things:

1. Copy and paste *exactly* the link you have in your additional board manager URLs field and paste it into a browser. Confirm you see a plain-text page that looks like this at the top
![image](https://user-images.githubusercontent.com/45793216/125666916-ecdbb7e1-daf9-41f4-8cab-a5b73acc27dd.png)

2.  Try installing the Arduino SAMD boards from the board manager and compile blink for the MKRZERO.

**Comment by jzwi** [comment]
Yes the pasted link is the same as what is shown here and on your set up tutorial. I think it has to be a firewall/network issue, the  board manager will no allow me to search, throws another error. The only available board is the default Arduino AVR

**Comment by AdamCummick** [comment]
Ah, that's a good sign it is a firewall issue then. All of Arduino's boards should show up in the board manager without additional setup.

**Comment by jzwi** [comment]
Okay thanks. Do you think the online editor could be a work around rather than dealing with the IT headache

**Comment by AdamCummick** [comment]
I'm that familiar with the online editor. We do have a [portable install instructions here](https://facts-engineering.github.io/faqs.html), though currently the P1AM library is a little old and the Arduino IDE is at 1.8.10. The core/board manager section is still good to go though. If anything, it is a good template on how to setup with your IDE.

**Comment by jzwi** [comment]
Okay thanks, the PLCs should be in soon. Was hoping to get the code ready to upload before they come in. Once they are I will play around with the couple different options. I will let you know if I need any help or additional questions answered.

**Comment by AdamCummick** [comment]
Sounds good. In the future, the best place to get answers for things like this would be the [AutomationDirect forum].(https://community.automationdirect.com/)
