### ISSUE TITLE
Error in downloading

### ISSUE THREAD

**Issue by csof27** [facts-engineering/P1AM#12]
I am trying to download the board manager but every time I type or copy the URL to the board manager it comes up with an error code. I was running it on 1.8.15, where no other board managers would load, but downloaded the legacy version of 1.8.7 where it still came up with an error message even though other ones loaded. I have followed the instructions on the other page as closely as possible and have attempted this on multiple computers, all coming up with the same error. Any advice on how to fix this issue?

**Comment by AdamCummick** [comment]
What operating system are you running?
Are you on a network managed by IT that might have firewall restrictions?

**Comment by csof27** [comment]
I am on windows 10 and I am on a network managed by IT.
