### ISSUE TITLE
P1-04THM configuration issue

### ISSUE THREAD

**Issue by colin-avro** [facts-engineering/P1AM#18]
I am attempting to read a load cell using the P1-04THM module configured for 0-39 mV.  When using the appropriate configuration array the resulting reading is consistently zero.  If I configure the channel as a thermocouple I see the reading change as force is applied to the load cell.  This indicates the sensor is connected and powered correctly but the THM module is behaving different with the 0-39 mV configuration.

**Comment by AdamCummick** [comment]
Are you able to share you code? I'm running the below and getting proper readings. The config string is set for 0-39mV on channel one and type J on 2-4.

```cpp
#include <P1AM.h>

float temperature;  //Variable for the temperature being read. "float" variables can store decimal values like 1.23
const char P1_04THM_CONFIG[] = { 0x40, 0x03, 0x60, 0x05, 0x21, 0x09, 0x22, 0x00, 0x23, 0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
void setup(){ // the setup routine runs once:

  Serial.begin(115200);  //initialize serial communication at 115200 bits per second 
  while (!P1.init()){ 
    ; //Wait for Modules to Sign on   
  }

  P1.configureModule(P1_04THM_CONFIG, 1);

}

void loop(){  // the loop routine runs over and over again forever:

  temperature = P1.readTemperature(1, 1);  //Return temperature read from channel 2 of the input module in slot 1
  
  Serial.print("Channel 1 Temperature: ");   
  Serial.println(temperature);  //print the value in degrees Fahrenheit up to 2 decimal places

  
  delay(1000);  //wait 1 second
  
}
```

**Comment by AdamCummick** [comment]
It could be Arduino truncating your float prints as it defaults to two decimal places. Try altering your print to `Serial.println(load_cell, 8); ` with 8 being the number of digits displayed after the decimal place.

**Comment by colin-avro** [comment]
Hi Adam,

Modifying the code as you suggested reveals that the value is changing to ~0.01.  This is consistent with the readTemperature function returning the value in volts.  Note that the documentation seems to imply the returned value is in millivolts. See here:
[https://facts-engineering.github.io/api_reference.html#readTemperature](url)

Thanks for your help! Appreciate the fast response time

**Comment by AdamCummick** [comment]
Good catch on the documentation, I'll make sure to get that corrected. Sorry for the confusion on that!
