### ISSUE TITLE
Pulse Counter Capabilities

### ISSUE THREAD

**Issue by szbrooks** [facts-engineering/P1AM#2]
Hi, 

I'm interested in using your device to take my prototype pulse counter into production, I have a few questions:

1. Can it support int64? 

Arduino's allow for uint64_t which will behave like an int64

2. How can I connect this information of the PLC to a computer?

I'd like to make a virtual serial connection and continuously send data to a program on the computer, is this feasible with your device?

Thank you!

**Comment by AdamCummick** [comment]
The P1AM-100 uses the same microcontroller (SAMD21) as the Arduino MKR family and other similar boards. 

It should allow a uint64_t. If you ever been to you can check by installing the board package and compiling code.

The board signs on to a PC as a virtual serial port that can be communicated with like any normal PC serial port.
