### ISSUE TITLE
platformio support?

### ISSUE THREAD

**Issue by simonvanderveldt** [facts-engineering/P1AM#3]
Hi! First of all thanks for this awesome project!

I was wondering if you'd be open to adding platformio support?
For the library it's nothing more than [registering it](https://docs.platformio.org/en/latest/librarymanager/creating.html#register). I guess I could do it myself, but since it's your project I figured it would be better to ask first.

For the board itself it seems like [adding a JSON config for the board ](https://docs.platformio.org/en/stable/platforms/creating_board.html) would be enough. I don't know how different the P1AM is from a regular Arduino MKR Zero, so maybe that would just work?

P.S. I have some questions/suggestions about the hardware as well. What would be the best place to share them?

**Comment by AdamCummick** [comment]
Thanks for reaching out. 

It looks like we should already be registered with platformio, let me know if that's not the case: https://platformio.org/lib/show/6909/P1AM/installation

For installing the board see my post here for a workaround:  https://forum.automationdirect.com//forum/open-source-devices/productivityopen-p1am/128015-p1am-getting-started?p=128939#post128939

I have an issue open with platformio to get the board formally added in: https://github.com/platformio/platform-atmelsam/issues/98

For general suggestions, the P1AM forum is the place, but I will email you shortly as well: https://forum.automationdirect.com/forum/open-source-devices/productivityopen-p1am

**Comment by simonvanderveldt** [comment]
Hi Adam,

Thanks for the quick response and the clear answers!

> It looks like we should already be registered with platformio, let me know if that's not the case: https://platformio.org/lib/show/6909/P1AM/installation

You're totally right, I missed it because I searched under AVR instead of SAMD, so totally my mistake.


> For installing the board see my post here for a workaround: https://forum.automationdirect.com//forum/open-source-devices/productivityopen-p1am/128015-p1am-getting-started?p=128939#post128939
> 
> I have an issue open with platformio to get the board formally added in: [platformio/platform-atmelsam#98](https://github.com/platformio/platform-atmelsam/issues/98)

Thanks for the pointers. Just diffed the board config from the forum post vs MKR ZERO and it's only names and hardware ID's which differ, nice to see that it's so close to a regular MKR ZERO.

I'd expect a PR for the platformio SAM repo would get merged quickly. Are you planning to create one? Otherwise I can do it as well.

> For general suggestions, the P1AM forum is the place, but I will email you shortly as well: https://forum.automationdirect.com/forum/open-source-devices/productivityopen-p1am

I'll have another look at the forums. Thanks for reaching out and for your help!

**Comment by patrickwasp** [comment]
Hi @AdamCummick, can we have the P1AM as a supported board in platformIO instead of just a library? It helps by including any necessary toolchain configurations and libraries automatically. In other words, I'd like to be able to find the P1AM in the board explorer. 

This is where board support is tracked
- https://github.com/platformio/platformio-core/labels/board

Thanks

**Comment by alecwhardy-idex** [comment]
Hi @AdamCummick , I'm trying to use PlatformIO with P1AM and P1AM_Serial, and I'm having the issue with Serial2 not being declared.  Can you give me some pointers on how to use [P1AMCore ](https://github.com/facts-engineering/P1AMCore) with PIO so it will compile?
