### ISSUE TITLE
Configuration for Read Temperature

### ISSUE THREAD

**Issue by MechanicalMe** [facts-engineering/P1AM#5]
Hello folks,

I was having trouble configuring a P1-04THM module with a K-type thermocouple and unit of C. Using the "ReadTemperature" example, it didn't show where or how to input the configuration constant that the website generates. 

The fix is to use P1.configureModule in the setup, which wasn't shown on the website. This is the modified example. 

/*
  Example: ReadTemperature
  
  This example shows how to read temperature values in degrees from a temperature input module. 
  The readTemperature function is also used when a temperature module is using a voltage or
  resistance range as it still returns a floating point value.
  
  Temperature inputs are analog inputs that read data from a temperature sensor and convert it into a 
  temperature reading. These include thermistors, thermocouples and resistance temperature detectors (RTDs) 
  
  This example works with all P1000 Series:
   - Temperature input modules such as P1-04NTC, P1-04RTD, and P1-04THM.
  
  The default ranges are:
   - P1-04THM: J-Type
   - P1-04RTD: Pt100
   - P1-04NTC: 2252
  
  This example will print channel 2's temperature to the serial monitor every second.
  This can be tested by:
   - Using an appropriate temperature probe for the module
   - Shorting the positive and negative inputs of a THM module to read room temperature.
   - Using a potentiometer to simulate thermistor/RTD signal on an NTC or RTD
      module and using a temp. vs. resistance chart to verify values. 
	  
     
  The reported temperature defaults to degrees Fahrenheit. 
	 _____  _____ 
	|  P  ||  S  |
	|  1  ||  L  |
	|  A  ||  O  |
	|  M  ||  T  |
	|  -  ||     |
	|  1  ||  0  |
	|  0  ||  1  |
	|  0  ||     |
	 ¯¯¯¯¯  ¯¯¯¯¯ 
	Written by FACTS Engineering
	Copyright (c) 2019 FACTS Engineering, LLC
	Licensed under the MIT license.
*/

#include <P1AM.h>

//this is the configured data from the website
const char _PBVAR_1_ConfigureP104THM_4[] = {
  0x40, 0x03, 
  0x60, 0x01,
  0x21, 0x01,
  0x22, 0x01,
  0x23, 0x01,
  0x24, 0x01,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

float temperature1;  //Variable for the temperature being read. "float" variables can store decimal values like 1.23
float temperature2;  //Variable for the temperature being read. "float" variables can store decimal values like 1.23
float temperature3;  //Variable for the temperature being read. "float" variables can store decimal values like 1.23

void setup(){ // the setup routine runs once:
  
  Serial.begin(115200);  //initialize serial communication at 115200 bits per second 
  while (!P1.init()){ 
     ; //Wait for Modules to Sign on   
  }
  P1.configureModule(_PBVAR_1_ConfigureP104THM_4, 4); // configures module on slot 4
  
}

void loop(){  // the loop routine runs over and over again forever:
  
 temperature1 = P1.readTemperature(4, 1);  //Look at input module in slot 4, Return temperature read from channel 1 
 temperature2 = P1.readTemperature(4, 2);  //Look at input module in slot 4, Return temperature read from channel 2 
 temperature3 = P1.readTemperature(4, 3);  //Look at input module in slot 4, Return temperature read from channel 3

  Serial.print("Channel 1 Temperature: ");   
  Serial.println(temperature1, 2);  //print the value in degrees Fahrenheit up to 2 decimal places
  Serial.print("Channel 2 Temperature: ");   
  Serial.println(temperature2, 2);  //print the value in degrees Fahrenheit up to 2 decimal places
  Serial.print("Channel 3 Temperature: ");   
  Serial.println(temperature3, 2);  //print the value in degrees Fahrenheit up to 2 decimal places
  
  delay(1000);  //wait 1 second
  
}

**Comment by AdamCummick** [comment]
Hey @MechanicalMe, 

Were you able to get everything working properly?

For module configuration we use the [ModuleConfiguration Exampe](https://github.com/facts-engineering/P1AM/blob/master/examples/Utility/ModuleConfiguration/ModuleConfiguration.ino)
We try to keep these base examples as simple as possible so they are flexible between many module types.

Thanks
Adam

**Comment by MechanicalMe** [comment]
Hey @AdamCummick ,

I did, it just took awhile and I wanted to save everyone else some time. 

Thanks!

**Comment by AdamCummick** [comment]
That's a good point, thanks for mentioning this. I'll look at adding at least a link to the configuration example in this code.
