### ISSUE TITLE
Power P1AM with Battery

### ISSUE THREAD

**Issue by szbrooks** [facts-engineering/P1AM#6]
Do you have any suggestions on how to configure the PLC to switch to battery power in the case of a power outage?

**Comment by AdamCummick** [comment]
That's pretty application dependent so it may be worth asking in the [ADC Forum](https://community.automationdirect.com/). I'm not familiar with battery based systems, so others may have better recommendations.

If you need to keep PLC IO operational, you'll need to provide an adequate 24V supply from battery. You also may want to call the `isBaseActive()` function to make sure you haven't lost 24V during the switchover. 

If you just need to keep the SAMD21 side alive, you could look at creating a circuit on the P1AM proto and supplying a regulated 5V to the VIN pin. This design wasn't optimized for battery operation, so you may want to check any leakages and the current consumption and account for those in a design. 

Thanks
Adam
