### ISSUE TITLE
writePWM Bug

### ISSUE THREAD

**Issue by AdamCummick** [facts-engineering/P1AM#8]
Writing to PWM module using "void P1AM::writePWM(float duty,uint32_t freq,uint8_t slot,uint8_t channel)" function causes incorrect behaviour. Offsets were incorrectly counted and ignored the first A0 module bytes. Fix for bug appears to be in lines 562-567
```	
for(int i=0;i<slot-1;i++){
		tempLoc = baseSlot[i].dbLoc;
		if(mdb[tempLoc].aoBytes > 0){
			offset += mdb[tempLoc].aoBytes;		//get offset of analog bytes
		}
	}
```

**Comment by kumataru** [comment]
Issue fixed in PR #9 [https://github.com/facts-engineering/P1AM/pull/9](https://github.com/facts-engineering/P1AM/pull/9)
